# Generated by Django 5.2.6 on 2025-09-29 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('user_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binder',
            name='sets',
        ),
        migrations.AlterField(
            model_name='binder',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BinderSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='user_collections.binder')),
                ('mtg_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.mtgset')),
            ],
            options={
                'unique_together': {('binder', 'mtg_set')},
            },
        ),
    ]
