# Generated by Django 5.2.6 on 2025-09-28 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MTGSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('card_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['dex_number'],
            },
        ),
        migrations.CreateModel(
            name='MTGCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('collector_number', models.CharField(max_length=10)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='games.mtgset')),
            ],
        ),
    ]
