# Generated by Django 5.2.6 on 2025-09-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgset',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
