# Generated by Django 5.2.6 on 2025-10-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_mtgset_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtgset',
            name='symbol_url',
            field=models.URLField(blank=True, help_text='URL to the set symbol image'),
        ),
    ]
